### ISSUE TITLE
demo doesn't do anything

### ISSUE THREAD

**Issue by ralyodio** [rtheunissen/rockets-demo#1]
I just get this:

```
$ npm start

> rockets-demo@1.0.3 start /Users/username/projects/tmp/rockets-demo
> node index.js
```

Am I supposed to be seeing something here?

**Comment by rtheunissen** [comment]
Nope, that's all there is. I'm currently trying to fix a bug in the server. See https://github.com/rockets/rockets/issues/2

**Comment by rtheunissen** [comment]
Server has been fixed. :)
